version: '3.8'

services:
  frontend-service:
    build:
      context: ./frontend
    container_name: frontend_container
    expose:
      - 5000
  backend-service:
    build:
      context: ./backend
    container_name: backend_container
    environment:
      - REDIS_HOST=redis-service
      - POSTGRES_HOST=database-service
      - POSTGRES_PASSWORD=secretpass
    expose:
      - 8080
    depends_on:
      - database-service
      - redis-service
  redis-service:
    image: redis
    container_name: redis_container
    expose:
      - 6379
  database-service:
    image: postgres:14-alpine
    container_name: database_container
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secretpass
    expose:
      - 5432
  nginx-service:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "80:80"
    container_name: nginx_container
    depends_on:
      - frontend-service
      - backend-service
      - redis-service
      - database-service