version: '3.8'

services:
  app:
    image: garudkar/express-app
    ports:
      - "8080:8080"
    container_name: app-container
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock